let monika = new Monika();
monika.InitGame();
let justmonika = new JustMonika(monika, 20,monika.getSize()[1]/2-10);
monika.addRenderObject(justmonika);
monika.setPlayer(justmonika);
let el = new EventListener(monika);
el.addListener(justmonika);
let op = new ObstaclePool(monika);
monika.addRenderObject(op);
monika.start();